### ISSUE TITLE
Unhandled Promise rejection: Cannot read property 'ExifInterface' of undefined

### ISSUE THREAD

**Issue by jorgeartigas** [nstudio/nativescript-camera-plus#59]
When taking a pic i'm getting this error:

`Unhandled Promise rejection: Cannot read property 'ExifInterface' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'ExifInterface' of undefined TypeError: Cannot read property 'ExifInterface' of undefined`

    at Object.getOrientationFromBytes (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/helpers.js:157:42)

    at CameraPlus.<anonymous> (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/camera-plus.js:1013:50)

    at step (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:101:35)

    at Object.next (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:48:28)

    at file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:29:79

    at new ZoneAwarePromise (file:///data/data/com.mypackage.pg/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)

    at global.__awaiter (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:5:20)

    at CameraPlus._finishSavingAndConfirmingPicture (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/camera-plus.js:990:16)

    at CameraPlus._onPictureTaken (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/camera-plus.js:976:18)

    at CameraPlus.<anonymous> (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/camera-plus.js:166:30)

    at step (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:101:35)

    at Object.next (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:48:28)

    at file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:29:79

    at new ZoneAwarePromise (file:///data/data/com.mypackage.pg/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js:902:29)

    at global.__awaiter (file:///data/data/com.mypackage.pg/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:5:20)`

**TNS info:**
Nativescript: 5.0
Tns-core-modules: 5.0.1
Tns-android: 5.0
Android-sdk: 23

**Comment by norainmatidris** [comment]
hi, im also having this error message. can someone help?

JS: NativeScript-CameraPlus --- [supported focus modes = [fixed] --- device: LENOVO Lenovo P90 on SDK: 19]
JS: NativeScript-CameraPlus --- [*** _setCameraDisplayOrientation ***]
JS: NativeScript-CameraPlus --- [DISPLAY ROTATION = 0]
JS: NativeScript-CameraPlus --- [--- setting rotation for front facing camera ---
JS:  --- info.orientation = 270]
JS: NativeScript-CameraPlus --- [result = 90]
JS: NativeScript-CameraPlus --- [targetRatio = 0.6944444444444444]
JS: NativeScript-CameraPlus --- [targetHeight = 750]
JS: NativeScript-CameraPlus --- [size.width = 960, size.height = 720]
JS: NativeScript-CameraPlus --- [ratio = 1.3333333333333333]
JS: NativeScript-CameraPlus --- [size.width = 1024, size.height = 576]
JS: NativeScript-CameraPlus --- [ratio = 1.7777777777777777]
JS: NativeScript-CameraPlus --- [size.width = 720, size.height = 480]
JS: NativeScript-CameraPlus --- [ratio = 1.5]
JS: NativeScript-CameraPlus --- [size.width = 640, size.height = 480]
JS: NativeScript-CameraPlus --- [ratio = 1.3333333333333333]
JS: NativeScript-CameraPlus --- [size.width = 640, size.height = 360]
JS: NativeScript-CameraPlus --- [ratio = 1.7777777777777777]
JS: NativeScript-CameraPlus --- [size.width = 352, size.height = 288]
JS: NativeScript-CameraPlus --- [ratio = 1.2222222222222223]
JS: NativeScript-CameraPlus --- [size.width = 320, size.height = 240]
JS: NativeScript-CameraPlus --- [ratio = 1.3333333333333333]
JS: NativeScript-CameraPlus --- [size.width = 176, size.height = 144]
JS: NativeScript-CameraPlus --- [ratio = 1.2222222222222223]
JS: NativeScript-CameraPlus --- [size.width = 184, size.height = 104]
JS: NativeScript-CameraPlus --- [ratio = 1.7692307692307692]
JS: NativeScript-CameraPlus --- [size.width = 960, size.height = 720]
JS: NativeScript-CameraPlus --- [size.width = 1024, size.height = 576]
JS: NativeScript-CameraPlus --- [size.width = 720, size.height = 480]
JS: NativeScript-CameraPlus --- [size.width = 640, size.height = 480]
JS: NativeScript-CameraPlus --- [size.width = 640, size.height = 360]
JS: NativeScript-CameraPlus --- [size.width = 352, size.height = 288]
JS: NativeScript-CameraPlus --- [size.width = 320, size.height = 240]
JS: NativeScript-CameraPlus --- [size.width = 176, size.height = 144]
JS: NativeScript-CameraPlus --- [size.width = 184, size.height = 104]
JS: NativeScript-CameraPlus --- [optimalSize = android.hardware.Camera$Size@1df3490, optimalSize.width = 960, optimalSize.height = 720]
JS: NativeScript-CameraPlus --- [mPreviewSize = android.hardware.Camera$Size@1df3490]
JS: NativeScript-CameraPlus --- [targetHeight = 750]
JS: NativeScript-CameraPlus --- [targetWidth = 750]
JS: NativeScript-CameraPlus --- [setting size width, 1024]
JS: NativeScript-CameraPlus --- [setting size height, 768]
JS: NativeScript-CameraPlus --- [optimalPictureSize = android.hardware.Camera$Size@1ff2700, optimalPictureSize.width = 1024, optimalPictureSize.height = 768]
JS: NativeScript-CameraPlus --- [mPictureSize = android.hardware.Camera$Size@1ff2700]
JS: NativeScript-CameraPlus --- [supported flash modes = [off] --- device: LENOVO Lenovo P90 on SDK: 19]
JS: NativeScript-CameraPlus --- [_ensureCorrectFlashIcon flash mode, off]
JS: Unhandled Promise rejection: Cannot read property 'ExifInterface' of undefined ; Zone: <root> ; Task: null ; Value: TypeError: Cannot read property 'ExifInterface' of undefined TypeError: Cannot read property 'ExifInterface' of undefined
JS:     at Object.getOrientationFromBytes (file:///data/data/org.nativescript.Beacon/files/app/tns_modules/@nstudio/nativescript-camera-plus/helpers.js:157:42)
JS:     at CameraPlus.<anonymous> (file:///data/data/org.nativescript.Beacon/files/app/tns_modules/@nstudio/nativescript-camera-plus/camera-plus.js:1018:50)
JS:     at step (file:///data/data/org.nativescript.Beacon/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:101:35)
JS:     at Object.next (file:///data/data/org.nativescript.Beacon/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:48:28)
JS:     at file:///data/data/org.nativescript.Beacon/files/app/tns_modules/@nstudio/nativescript-camera-plus/async-await.js:29:79
JS:     at new ZoneAwarePromise (file:///data/data/org.nativescript.Beacon/files/...

**Comment by jorgeartigas** [comment]
I'm no longer having this issue, I don't know why but it got fixed

**Comment by norainmatidris** [comment]
i am still having this issue.

**Comment by bradmartin** [comment]
Make sure your android sdk and build tools are updated. Then perform a clean build and all should be okay.

ExitInterface is coming in as a dependency here (https://github.com/nstudio/nativescript-camera-plus/blob/b0021c9808b6bd3b0de403bb6044a7738805f742/src/platforms/android/include.gradle#L6)

**Comment by norainmatidris** [comment]
i do have this dependency. how can i update the android sdk?

**Comment by bradmartin** [comment]
I use android studio to update build tools and android sdks. There are other options though.

**Comment by geoffbullen** [comment]
I get this on my android device (sdk 23), but not an emulator (sdk 28).    I have updated the android sdk on my PC.

**Comment by geoffbullen** [comment]
As this came in with Android 25, I guess this plugin has a requirement that we user v25 and above...   A slight shame.

https://android-developers.googleblog.com/2016/12/introducing-the-exifinterface-support-library.html
